import { Link } from "react-router-dom"
import { useStore } from "../store/useStore"
import { Button } from "../components/ui/Button"
import { BookOpen, BarChart } from "lucide-react"

export default function CoursesPage() {
    const courses = useStore((state) => state.courses)

    return (
        <div className="container mx-auto px-4 py-12 flex-1">
            <div className="mb-10 text-center max-w-3xl mx-auto">
                <h1 className="text-4xl font-extrabold tracking-tight mb-4">Explore AI Courses</h1>
                <p className="text-lg text-muted-foreground text-balance">
                    Discover structured learning paths generated by cutting-edge AI. Enhance your skills across programming, design, and artificial intelligence completely free.
                </p>
            </div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                {courses.filter(c => c.isPublished).map((course) => (
                    <div key={course.id} className="group flex flex-col bg-card border rounded-2xl overflow-hidden hover:shadow-md transition-all">
                        <div className="aspect-video bg-muted overflow-hidden relative">
                            {course.bannerUrl ? (
                                <img
                                    src={course.bannerUrl}
                                    alt={course.title}
                                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                                />
                            ) : (
                                <div className="w-full h-full flex items-center justify-center bg-primary/5 text-primary">
                                    <BookOpen className="h-10 w-10 opacity-50" />
                                </div>
                            )}
                            <div className="absolute top-3 right-3 bg-background/90 backdrop-blur-sm px-2.5 py-1 rounded-full text-xs font-medium border shadow-sm flex items-center capitalize">
                                <BarChart className="h-3 w-3 mr-1 inline" />
                                {course.level}
                            </div>
                        </div>

                        <div className="p-5 flex flex-col flex-1">
                            <h3 className="font-bold text-lg mb-2 line-clamp-1">{course.title}</h3>
                            <p className="text-sm text-muted-foreground line-clamp-2 mb-4 flex-1">
                                {course.description}
                            </p>

                            <div className="flex items-center justify-between mt-auto">
                                <div className="text-xs text-muted-foreground font-medium flex items-center">
                                    By {course.creatorName || "AI Instructor"}
                                </div>
                                <Button size="sm" asChild className="rounded-full px-5">
                                    <Link to={`/courses/${course.id}`}>Take Course</Link>
                                </Button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
        </div>
    )
}
